on:
  push:
    branches:
      - master

 

 job:
   build:
     runs-on: ubuntu-latest


     steps:
       - name: 'Testing Github action'
         run: pwd


       - name: 'Testing Printing'
         run: echo Rahma